# Special .cirrus.yml file to test combination of AIO/DIO features.  WIP.

env:
  # accelerate initial clone
  CIRRUS_CLONE_DEPTH: 1
  # target to test, for all but OSX and windows
  CHECK: check-world
  CHECKFLAGS: -Otarget
  PGCTLTIMEOUT: 120


task:
  windows_container:
    dockerfile: ci/WindowsDockerfile
    cpu: 4
    memory: 4G
  env:
    PROVE_FLAGS: -j10
    # Avoid re-installing over and over
    NO_TEMP_INSTALL: 1
    TIMEOUT_CMD: timeout -k60s 30m

  matrix:
    - name: Windows Worker Buf
      env:
        TEMP_CONFIG: ${CIRRUS_WORKING_DIR}\ci\worker_buf.conf
    - name: Windows Worker DIO
      env:
        TEMP_CONFIG: ${CIRRUS_WORKING_DIR}\ci\worker_dio.conf
  test_script:
    - powershell -Command get-psdrive -psprovider filesystem
    - set

  config_script:
    - copy ci\windows_build_config.pl src\tools\msvc\config.pl
    - vcvarsall x64
    - perl src/tools/msvc/mkvcbuild.pl
  build_script:
    - set IgnoreWarnIntDirInTempDetected=true
    - vcvarsall x64
    - msbuild -m pgsql.sln
  install_script:
    - perl src\tools\msvc\install.pl tmp_install

  check_script:
    - timeout -k60s 30m perl src/tools/msvc/vcregress.pl check parallel

  ecpgcheck_script:
    # tries to build additional stuff
    - vcvarsall x64
    # References ecpg_regression.proj in the current dir
    - cd src\tools\msvc
    - timeout -k60s 30m perl vcregress.pl ecpgcheck

  startcreate_script:
    - tmp_install\bin\pg_ctl.exe initdb -D tmp_check\db -l tmp_check\initdb.log
    - tmp_install\bin\pg_ctl.exe start -D tmp_check\db -l tmp_check\postmaster.log
  modulescheck_script:
    - timeout -k60s 30m perl src/tools/msvc/vcregress.pl modulescheck
  isolationcheck_script:
    - timeout -k60s 30m perl src/tools/msvc/vcregress.pl isolationcheck
  contribcheck_script:
    - timeout -k60s 30m perl src/tools/msvc/vcregress.pl contribcheck
  plcheck_script:
    - timeout -k60s 30m perl src/tools/msvc/vcregress.pl plcheck
  stop_script:
    # XXX: should ensure this gets called if previous steps fail
    - tmp_install\bin\pg_ctl.exe stop -D tmp_check\db -l tmp_check\postmaster.log
  recoverycheck_script:
    - timeout -k60s 30m perl src/tools/msvc/vcregress.pl recoverycheck
  bincheck_script:
    - timeout -k60s 30m perl src/tools/msvc/vcregress.pl bincheck
  upgradecheck_script:
    - timeout -k60s 30m perl src/tools/msvc/vcregress.pl upgradecheck
  on_failure:
    log_artifacts:
      path: "**/**.log"
      type: text/plain
    regress_diffs_artifacts:
      path: "**/**.diffs"
      type: text/plain
    tap_artifacts:
      path: "**/regress_log_*"
      type: text/plain
